version: "2.3"
services:

  acfront:
    build: ./frontend
    container_name: acfront
    command: >
      sh -c "yarn run lint -- --fix && \
             yarn build"
    volumes:
     - ./frontend/airconditioner:/airconditioner
    ports:
     - "8001:8080"
