version: "2.3"
services:

  acfront:
    build: ./frontend
    container_name: acfront
    command: yarn build
    volumes:
     - ./frontend/airconditioner:/airconditioner
    ports:
     - "8001:8080"
    restart: unless-stopped

  acback:
    build: ./backend
    container_name: acback
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate &&
             python manage.py create_django_admin_user &&
             coverage run manage.py test -v 3 --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
     - ./backend/airconditioner:/airconditioner
    ports:
     - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env.dev
    depends_on:
      - acfront
