# Generated by Django 4.0.4 on 2022-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_controlprofile_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlprofile',
            name='swing',
            field=models.BooleanField(default=False),
        ),
    ]
