# Generated by Django 4.0.4 on 2022-04-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_controlprofile_swing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlprofile',
            name='options',
        ),
        migrations.AddField(
            model_name='controlprofile',
            name='option',
            field=models.CharField(choices=[('2-Step', 'Two Step'), ('Fast', 'Fast'), ('Confort', 'Confort'), ('Single User', 'Single User'), ('Quiet', 'Quiet'), ("D'light Cool", 'Dlight Cool'), ('Virus Doctor', 'Virus Doctor')], default='Quiet', max_length=12),
        ),
    ]
