# Generated by Django 4.0.4 on 2022-04-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_remove_controlprofile_options_controlprofile_option'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='controlprofile',
            unique_together={('temperature', 'mode', 'option', 'swing')},
        ),
    ]
