# Generated by Django 4.0.4 on 2022-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_controlprofile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
