# Generated by Django 4.0.4 on 2022-07-22 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_remove_controlprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditionerStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
