# Generated by Django 4.0.4 on 2022-07-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_airconditionerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlprofile',
            name='swing',
            field=models.BooleanField(default=True),
        ),
    ]
